apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalog-worker
  name: catalog-worker
  namespace: staging

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: catalog-worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: catalog-worker
    spec:
      containers:
      - image: **********.dkr.ecr.eu-west-1.amazonaws.com/catalog-worker:staging-15
        imagePullPolicy: Always
        name: catalog-worker
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
